services:
  backend:
    build: ./backend
    container_name: django_backend
    env_file:
      - ./backend/.env 
    ports:
      - 8000:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume: