# Generated by Django 5.2.13 on 2026-05-13 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_category_date_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='idx_post_category_date',
            old_name='post_category_date_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='idx_post_category'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='idx_post_created_at'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='idx_post_author'),
        ),
    ]
