# Generated by Django 5.2.13 on 2026-05-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_category_date_idx_idx_post_category_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='idx_post_category',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_post_author',
        ),
    ]
