# Generated by Django 4.2.6 on 2026-01-25 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_rename_by_user_notification_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='from_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='reaction_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='grouped_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
