# Generated by Django 4.2.6 on 2026-01-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usernname',
        ),
    ]
